"use client";
import Editor from "@monaco-editor/react";
import {useEffect,useMemo,useRef,useState} from "react";

type Files=Record<string,string>;type Mode="Ask"|"Plan"|"Agent"|"Debug";type Panel="TERMINAL"|"PROBLEMS"|"OUTPUT"|"BROWSER"|"GIT"|"DEPLOYMENT";
type Chat={role:"user"|"agent"|"system";text:string;meta?:string};type Change={path:string;before:string;after:string;accepted:boolean};
const seed:Files={
 "src/app.ts":"import { createServer } from './server';\n\nconst app = createServer({ port: 3000 });\napp.start();\n",
 "src/server.ts":"export function createServer(config: { port: number }) {\n  return { start() { console.log(`OpenTrue running on :${config.port}`); } };\n}\n",
 "src/auth.ts":"export async function verifySession(sessionId: string) {\n  return Boolean(sessionId);\n}\n",
 "tests/auth.test.ts":"import { verifySession } from '../src/auth';\n\ntest('rejects empty session', async () => {\n  expect(await verifySession('')).toBe(false);\n});\n",
 "README.md":"# OpenTrue Code\n\nChat-first, local-first AI coding workspace.\n"
};
const ext=(p:string)=>p.split(".").pop()?.toLowerCase()||"",lang=(p:string)=>["ts","tsx"].includes(ext(p))?"typescript":ext(p)==="js"?"javascript":ext(p)==="json"?"json":"markdown";
const icons:Record<string,string>={ts:"TS",tsx:"TS",js:"JS",json:"{}",md:"M↓",css:"#",html:"<>"};
function completion(source:string,offset:number){const prefix=source.slice(Math.max(0,offset-12000),offset);const part:string=prefix.split(/\r?\n/).at(-1)?.match(/[A-Za-z_$][\w$]*$/)?.[0]??"";if(part.length<2)return null;const words:string[]=prefix.match(/[A-Za-z_$][\w$]*/g)??[];const found=words.filter(x=>x!==part&&x.startsWith(part));return found.at(-1)?.slice(part.length)||null}
function FileIcon({path}:{path:string}){return <i className={"fileIcon "+ext(path)}>{icons[ext(path)]||"·"}</i>}

export default function Home(){
 const [files,setFiles]=useState<Files>(seed),[active,setActive]=useState("src/app.ts"),[tabs,setTabs]=useState(["src/app.ts","src/auth.ts"]),[dirty,setDirty]=useState(new Set<string>());
 const [activity,setActivity]=useState("files"),[side,setSide]=useState(true),[chatOpen,setChatOpen]=useState(true),[bottomOpen,setBottomOpen]=useState(true),[panel,setPanel]=useState<Panel>("TERMINAL");
 const [sideW,setSideW]=useState(248),[chatW,setChatW]=useState(390),[bottomH,setBottomH]=useState(220),[mobile,setMobile]=useState<"code"|"files"|"chat"|"tasks"|"preview">("code");
 const [mode,setMode]=useState<Mode>("Agent"),[prompt,setPrompt]=useState(""),[sending,setSending]=useState(false),[palette,setPalette]=useState(false),[inline,setInline]=useState(false),[query,setQuery]=useState("");
 const [messages,setMessages]=useState<Chat[]>([{role:"system",text:"Workspace indexed · 5 files · 4 symbols",meta:"Local context ready"},{role:"agent",text:"Ready. I can edit multiple files, run checks, preview the result, and prepare a pull request.",meta:"qwen3-coder:30b · local"}]);
 const [changes,setChanges]=useState<Change[]>([]),[terminal,setTerminal]=useState("$ npm test\n✓ auth.test.ts\n✓ repository indexed\n\nTests: 1 passed\nTime: 0.42s\n$ ");
 const disposer=useRef<{dispose:()=>void}|null>(null);
 useEffect(()=>{const saved=localStorage.getItem("opentrue.workspace.v3");if(saved)try{setFiles(JSON.parse(saved))}catch{};const keys=(e:KeyboardEvent)=>{if((e.metaKey||e.ctrlKey)&&e.shiftKey&&e.key.toLowerCase()==="p"){e.preventDefault();setPalette(x=>!x)}if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==="k"){e.preventDefault();setInline(true)}if((e.metaKey||e.ctrlKey)&&e.key==="\`"){e.preventDefault();setBottomOpen(x=>!x)}};window.addEventListener("keydown",keys);return()=>window.removeEventListener("keydown",keys)},[]);
 useEffect(()=>localStorage.setItem("opentrue.workspace.v3",JSON.stringify(files)),[files]);
 const value=files[active]||"",folders=useMemo(()=>{const m=new Map<string,string[]>();Object.keys(files).sort().forEach(p=>{const f=p.includes("/")?p.split("/")[0]:"ROOT";m.set(f,[...(m.get(f)||[]),p])});return [...m]},[files]);
 function open(p:string){setActive(p);setTabs(t=>t.includes(p)?t:[...t,p]);setMobile("code")}
 function write(p:string,v:string){setFiles(f=>({...f,[p]:v}));setDirty(d=>new Set(d).add(p))}
 function add(){const p=window.prompt("New file path","src/untitled.ts")?.trim();if(p&&!files[p]){write(p,"");open(p)}}
 function rename(p:string){const n=window.prompt("Rename file",p)?.trim();if(!n||files[n])return;setFiles(f=>{const x={...f,[n]:f[p]};delete x[p];return x});setTabs(t=>t.map(x=>x===p?n:x));if(active===p)setActive(n)}
 function remove(p:string){if(!confirm("Delete "+p+"?"))return;setFiles(f=>{const x={...f};delete x[p];return x});setTabs(t=>t.filter(x=>x!==p))}
 function propose(task:string){const before=files["src/auth.ts"]||"",after=before.replace("return Boolean(sessionId);","if (!sessionId.trim()) return false;\n  return sessionId.length >= 12;");setChanges([{path:"src/auth.ts",before,after,accepted:true},{path:"tests/auth.test.ts",before:files["tests/auth.test.ts"]||"",after:(files["tests/auth.test.ts"]||"")+"\n\ntest('accepts valid session', async () => {\n  expect(await verifySession('session-valid-123')).toBe(true);\n});\n",accepted:true}]);setMessages(m=>[...m,{role:"user",text:task},{role:"agent",text:"I inspected authentication and prepared two coordinated edits. Review the diff before applying.",meta:"2 files · checkpoint ready"}]);setPanel("OUTPUT");setBottomOpen(true)}
 async function send(){const task=prompt.trim();if(!task)return;setPrompt("");setSending(true);setMessages(m=>[...m,{role:"user",text:task},{role:"system",text:"Analyzing repository…",meta:"index → symbols → tests"}]);await new Promise(r=>setTimeout(r,600));propose(task);setSending(false)}
 function apply(){changes.filter(x=>x.accepted).forEach(x=>write(x.path,x.after));setChanges([]);setMessages(m=>[...m,{role:"agent",text:"Selected edits applied. Checkpoint remains available for rollback.",meta:"Tests ready to run"}])}
 function resize(kind:"side"|"chat"|"bottom",e:React.PointerEvent){const sx=e.clientX,sy=e.clientY,sw=sideW,cw=chatW,bh=bottomH;const move=(x:PointerEvent)=>{if(kind==="side")setSideW(Math.max(180,Math.min(420,sw+x.clientX-sx)));else if(kind==="chat")setChatW(Math.max(320,Math.min(620,cw+sx-x.clientX)));else setBottomH(Math.max(120,Math.min(480,bh+sy-x.clientY)))};const up=()=>{window.removeEventListener("pointermove",move);window.removeEventListener("pointerup",up)};window.addEventListener("pointermove",move);window.addEventListener("pointerup",up)}
 const preview="<!doctype html><style>body{font:16px system-ui;background:#0b0d10;color:#e6eaf0;padding:32px}.card{padding:24px;border:1px solid #272b33;border-radius:12px;background:#111419}b{color:#9b9fff}</style><div class=card><b>OpenTrue Preview</b><h1>Build with Unlimited Chat</h1><p>Workspace is running.</p></div>";
 const commands=[["Toggle Explorer","⌘B",()=>setSide(x=>!x)],["Toggle Agent Chat","⌘⇧A",()=>setChatOpen(x=>!x)],["Inline Edit","⌘K",()=>setInline(true)],["Toggle Terminal","⌘\`",()=>setBottomOpen(x=>!x)],["Run tests","",()=>{setPanel("TERMINAL");setBottomOpen(true);setTerminal(t=>t+"npm test\n✓ all checks passed\n$ ")}]] as const;
 return <main className="shell">
  <header className="titlebar"><div className="traffic"><i/><i/><i/></div><button className="project">◇ opentrue-code⌄</button><button className="command" onClick={()=>setPalette(true)}>⌕ Search files or run a command <kbd>⌘⇧P</kbd></button><div className="topActions"><span>✦ Unlimited Chat</span><button>↗ Share</button><button className="primary">Upgrade</button></div></header>
  <div className="main">
   <nav className="activity">{[["files","▱","Explorer"],["search","⌕","Search"],["git","⑂","Source Control"],["tasks","◫","Tasks"],["extensions","⬡","Extensions"]].map(([id,ic,label])=><button aria-label={label} className={activity===id?"active":""} key={id} onClick={()=>{setActivity(id);setSide(true);if(id==="git"){setPanel("GIT");setBottomOpen(true)}}}><span>{ic}</span>{id==="git"&&dirty.size>0&&<b>{dirty.size}</b>}</button>)}<div/><button aria-label="Account">◎</button><button aria-label="Settings">⚙</button></nav>
   {side&&<aside className={"sidebar "+(mobile==="files"?"mobileShow":"")} style={{width:sideW}}><div className="paneTitle"><span>{activity==="git"?"SOURCE CONTROL":activity==="search"?"SEARCH":"EXPLORER"}</span><div><button onClick={add}>＋</button><button>•••</button></div></div>
    {activity==="search"?<div className="search"><input autoFocus value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search files"/>{Object.keys(files).filter(p=>p.includes(query)).map(p=><button key={p} onClick={()=>open(p)}><FileIcon path={p}/>{p}</button>)}</div>:activity==="git"?<div className="scm"><textarea placeholder="Message (⌘Enter)"/><button className="primary">Commit</button><h4>CHANGES <span>{dirty.size}</span></h4>{[...dirty].map(p=><button key={p} onClick={()=>open(p)}><span>M</span>{p}</button>)}</div>:<div className="tree"><button className="root">⌄ OPENTRUE-CODE</button>{folders.map(([folder,paths])=><section key={folder}><div className="folder">⌄ {folder}</div>{paths.map(p=><div className={"treeFile "+(p===active?"active":"")} key={p}><button onClick={()=>open(p)}><FileIcon path={p}/><span>{p.includes("/")?p.split("/").slice(1).join("/"):p}</span>{dirty.has(p)&&<em>●</em>}</button><div><button onClick={()=>rename(p)}>✎</button><button onClick={()=>remove(p)}>×</button></div></div>)}</section>)}</div>}<footer><button>⌄ OUTLINE</button><button>› TIMELINE</button></footer></aside>}
   {side&&<div className="resizeV" onPointerDown={e=>resize("side",e)}/>}
   <section className={"workbench "+(mobile==="code"?"mobileShow":"")}><div className="crumb">opentrue-code › {active.replaceAll("/"," › ")}</div><div className="tabs">{tabs.map(p=><button className={p===active?"active":""} key={p} onClick={()=>setActive(p)}><FileIcon path={p}/>{p.split("/").at(-1)}{dirty.has(p)&&<em>●</em>}<span onClick={e=>{e.stopPropagation();setTabs(t=>t.filter(x=>x!==p))}}>×</span></button>)}<button className="split">▥</button></div><div className="editor"><Editor theme="vs-dark" language={lang(active)} path={active} value={value} onChange={v=>write(active,v||"")} onMount={(ed,m)=>{m.editor.defineTheme("opentrue",{base:"vs-dark",inherit:true,rules:[{token:"comment",foreground:"6d7685",fontStyle:"italic"},{token:"keyword",foreground:"c792ea"},{token:"string",foreground:"c3e88d"}],colors:{"editor.background":"#0B0D10","editor.lineHighlightBackground":"#11151b","editorCursor.foreground":"#8b9cff","editor.selectionBackground":"#39405f88","editorLineNumber.foreground":"#444b57"}});m.editor.setTheme("opentrue");disposer.current?.dispose();disposer.current=m.languages.registerInlineCompletionsProvider(["typescript","javascript","json","markdown"],{provideInlineCompletions(model,pos){const insertText=completion(model.getValue(),model.getOffsetAt(pos));return {items:insertText?[{insertText,range:new m.Range(pos.lineNumber,pos.column,pos.lineNumber,pos.column)}]:[],dispose(){}}},freeInlineCompletions(){}});ed.addAction({id:"inline",label:"OpenTrue Inline Edit",keybindings:[m.KeyMod.CtrlCmd|m.KeyCode.KeyK],run:()=>setInline(true)})}} options={{fontSize:13,fontFamily:"'JetBrains Mono',monospace",lineHeight:21,automaticLayout:true,minimap:{enabled:true},smoothScrolling:true,inlineSuggest:{enabled:true},tabCompletion:"on",padding:{top:12}}}/>{inline&&<div className="inline"><span>✦</span><input autoFocus placeholder="Describe an edit…" onKeyDown={e=>{if(e.key==="Enter"){propose(e.currentTarget.value);setInline(false)}if(e.key==="Escape")setInline(false)}}/><kbd>Enter</kbd></div>}</div>
    {bottomOpen&&<><div className="resizeH" onPointerDown={e=>resize("bottom",e)}/><section className={"bottom "+(mobile==="preview"?"mobileShow":"")} style={{height:bottomH}}><div className="panelTabs">{(["TERMINAL","PROBLEMS","OUTPUT","BROWSER","GIT","DEPLOYMENT"] as Panel[]).map(x=><button className={panel===x?"active":""} key={x} onClick={()=>setPanel(x)}>{x}{x==="PROBLEMS"&&<b>0</b>}</button>)}<span/><button onClick={()=>setBottomOpen(false)}>⌄</button><button>□</button><button onClick={()=>setBottomOpen(false)}>×</button></div><PanelContent panel={panel} terminal={terminal} preview={preview} changes={changes} setChanges={setChanges} apply={apply} dirty={dirty}/></section></>}
   </section>
   {chatOpen&&<div className="resizeV" onPointerDown={e=>resize("chat",e)}/>}
   {chatOpen&&<aside className={"agent "+(mobile==="chat"?"mobileShow":"")} style={{width:chatW}}><div className="agentTitle"><div><span>✦</span><b>OpenTrue Agent</b></div><div><button>＋</button><button>◷</button><button>•••</button></div></div><div className="modes">{(["Ask","Plan","Agent","Debug"] as Mode[]).map(x=><button className={mode===x?"active":""} key={x} onClick={()=>setMode(x)}>{x}</button>)}</div><div className="connected"><i/> <b>Workspace connected</b><span>main · qwen3-coder:30b</span></div><div className="conversation">{messages.map((m,i)=><article className={m.role} key={i}>{m.role==="agent"&&<div className="avatar">✦</div>}<div><small>{m.role==="agent"?"OpenTrue":m.role==="user"?"You":"Activity"}</small><p>{m.text}</p>{m.meta&&<em>{m.meta}</em>}</div></article>)}{sending&&<article className="agentMsg"><div className="avatar">✦</div><div className="thinking"><i/><i/><i/></div></article>}{changes.length>0&&<div className="approval"><header><span>±</span><b>{changes.length} files changed</b></header>{changes.map(c=><button key={c.path} onClick={()=>open(c.path)}><FileIcon path={c.path}/>{c.path}<span>+1</span></button>)}<footer><button onClick={()=>setChanges([])}>Reject</button><button className="primary" onClick={apply}>Apply All</button></footer></div>}</div><div className="composer"><div><button>@ Codebase</button><button>＋ Context</button></div><textarea value={prompt} onChange={e=>setPrompt(e.target.value)} onKeyDown={e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();send()}}} placeholder={mode==="Ask"?"Ask about your codebase…":mode==="Plan"?"Describe what you want planned…":mode==="Debug"?"Describe the bug…":"Describe a change to build…"}/><footer><button>qwen3-coder:30b⌄</button><span>Local GPU · Queue ready</span><button className="send" disabled={!prompt.trim()||sending} onClick={send}>↑</button></footer></div><div className="unlimited"><span>✦ Unlimited Chat</span><span>No token balance</span><span>2/5 agents</span></div></aside>}
  </div>
  <footer className="status"><button>⑂ main*</button><button>↻</button><button>ⓧ 0</button><button>△ 0</button><span/><button>GPU <i/> Ready</button><button>Queue 0</button><button>qwen3-coder:30b</button><button>Ln 1, Col 1</button><button>{"{}"} TypeScript</button></footer>
  <nav className="mobileNav">{[["code","Code"],["files","Files"],["chat","Chat"],["tasks","Tasks"],["preview","Preview"]].map(([id,label])=><button className={mobile===id?"active":""} key={id} onClick={()=>{setMobile(id as typeof mobile);if(id==="files")setSide(true);if(id==="chat")setChatOpen(true);if(id==="preview"){setPanel("BROWSER");setBottomOpen(true)}}}>{label}</button>)}</nav>
  {palette&&<div className="paletteBg" onMouseDown={()=>setPalette(false)}><section className="palette" onMouseDown={e=>e.stopPropagation()}><header><span>›</span><input autoFocus placeholder="Type a command or search files" onKeyDown={e=>e.key==="Escape"&&setPalette(false)}/><kbd>esc</kbd></header><small>COMMANDS</small>{commands.map(([name,key,run])=><button key={name} onClick={()=>{run();setPalette(false)}}><span>{name}</span><kbd>{key}</kbd></button>)}</section></div>}
 </main>
}

function PanelContent({panel,terminal,preview,changes,setChanges,apply,dirty}:{panel:Panel;terminal:string;preview:string;changes:Change[];setChanges:React.Dispatch<React.SetStateAction<Change[]>>;apply:()=>void;dirty:Set<string>}){
 if(panel==="TERMINAL")return <div className="terminal"><header><button className="active">⌁ zsh ×</button><button>＋</button><span/><button>⌫</button><button>•••</button></header><pre>{terminal}</pre></div>;
 if(panel==="BROWSER")return <div className="browser"><header><button>←</button><button>→</button><button>↻</button><input value="http://localhost:3000" readOnly/><button>▣</button><button>◫</button></header><iframe title="Project preview" sandbox="allow-scripts" srcDoc={preview}/></div>;
 if(panel==="OUTPUT")return <div className="output">{changes.length?<><header><b>Proposed changes</b><span>{changes.length} files · checkpoint ready</span><button onClick={()=>setChanges([])}>Reject all</button><button className="primary" onClick={apply}>Apply all</button></header>{changes.map((c,i)=><article key={c.path}><label><input type="checkbox" checked={c.accepted} onChange={()=>setChanges(v=>v.map((x,j)=>i===j?{...x,accepted:!x.accepted}:x))}/>{c.path}</label><pre><del>- original implementation</del>{"\n"}<ins>+ validated implementation</ins></pre></article>)}</>:<Empty icon="✦" title="Agent output" text="Streamed tasks and proposed edits appear here."/>}</div>;
 if(panel==="GIT")return <div className="gitPanel"><header><b>main</b><span>Working tree · {dirty.size} change(s)</span></header><div><span className="done">✓ Branch</span>→<span className="done">✓ Edit</span>→<span className="done">✓ Test</span>→<span>Commit</span>→<span>Push</span>→<span>PR</span></div><button className="primary">Commit changes</button></div>;
 if(panel==="DEPLOYMENT")return <div className="deploy"><article><i className="ok"/><div><b>Staging</b><small>Healthy · exact SHA</small></div><button>View logs</button></article><article><i/><div><b>Production</b><small>Approval required</small></div><button>Request deploy</button></article></div>;
 return <Empty icon="✓" title={panel==="PROBLEMS"?"No problems detected":"Output stream ready"} text={panel==="PROBLEMS"?"TypeScript and lint diagnostics are clean.":"Commands and worker receipts appear here."}/>;
}
function Empty({icon,title,text}:{icon:string;title:string;text:string}){return <div className="empty"><span>{icon}</span><b>{title}</b><small>{text}</small></div>}
