BEGIN;
CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE TABLE IF NOT EXISTS tenants(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),name text NOT NULL,plan text NOT NULL DEFAULT 'free',created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS users(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),external_subject text UNIQUE NOT NULL,created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS memberships(tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,role text NOT NULL CHECK(role IN('owner','admin','developer','viewer')),PRIMARY KEY(tenant_id,user_id));
CREATE TABLE IF NOT EXISTS projects(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,name text NOT NULL,created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS jobs(id uuid PRIMARY KEY,tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,user_id uuid NOT NULL REFERENCES users(id),project_id uuid REFERENCES projects(id),target text NOT NULL,task text NOT NULL,args jsonb NOT NULL DEFAULT '[]',status text NOT NULL,attempt integer NOT NULL DEFAULT 0,max_attempts integer NOT NULL,timeout_ms integer NOT NULL,worker_id text,receipt jsonb,error text,created_at timestamptz NOT NULL,updated_at timestamptz NOT NULL);
CREATE INDEX IF NOT EXISTS jobs_tenant_status_created_idx ON jobs(tenant_id,status,created_at);
CREATE TABLE IF NOT EXISTS audit_events(id uuid PRIMARY KEY,tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,user_id uuid,action text NOT NULL,details jsonb NOT NULL DEFAULT '{}',created_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS audit_tenant_created_idx ON audit_events(tenant_id,created_at DESC);
CREATE TABLE IF NOT EXISTS usage_daily(tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,user_id uuid NOT NULL REFERENCES users(id),day date NOT NULL,jobs integer NOT NULL DEFAULT 0,active integer NOT NULL DEFAULT 0,compute_ms bigint NOT NULL DEFAULT 0,PRIMARY KEY(tenant_id,user_id,day));
CREATE TABLE IF NOT EXISTS secret_envelopes(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,name text NOT NULL,ciphertext jsonb NOT NULL,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),UNIQUE(tenant_id,name));
ALTER TABLE jobs ENABLE ROW LEVEL SECURITY;ALTER TABLE audit_events ENABLE ROW LEVEL SECURITY;ALTER TABLE projects ENABLE ROW LEVEL SECURITY;ALTER TABLE secret_envelopes ENABLE ROW LEVEL SECURITY;
ALTER TABLE jobs FORCE ROW LEVEL SECURITY;ALTER TABLE audit_events FORCE ROW LEVEL SECURITY;ALTER TABLE projects FORCE ROW LEVEL SECURITY;ALTER TABLE secret_envelopes FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS jobs_tenant ON jobs;CREATE POLICY jobs_tenant ON jobs USING(tenant_id=current_setting('app.tenant_id',true)::uuid);
DROP POLICY IF EXISTS audit_tenant ON audit_events;CREATE POLICY audit_tenant ON audit_events USING(tenant_id=current_setting('app.tenant_id',true)::uuid);
DROP POLICY IF EXISTS projects_tenant ON projects;CREATE POLICY projects_tenant ON projects USING(tenant_id=current_setting('app.tenant_id',true)::uuid);
DROP POLICY IF EXISTS secrets_tenant ON secret_envelopes;CREATE POLICY secrets_tenant ON secret_envelopes USING(tenant_id=current_setting('app.tenant_id',true)::uuid);
COMMIT;
