"use client";

import {useEffect,useMemo,useState} from "react";

type Mode="ask"|"plan"|"agent"|"debug";
type Output={stream:string;text:string};
type Job={id:string;status:string;target:string;task:string;attempt:number;maxAttempts:number;receipt?:{exitCode:number;durationMs:number;outputHash?:string;output?:Output[]}|null;error?:string|null};
const terminal=new Set(["SUCCEEDED","FAILED","CANCELLED","TIMED_OUT"]);
const card={background:"#111827",border:"1px solid #263247",borderRadius:12,padding:16} as const;
const field={width:"100%",boxSizing:"border-box" as const,background:"#07101f",color:"#e5e7eb",border:"1px solid #374151",borderRadius:8,padding:"10px 11px"};
const btn={border:0,borderRadius:8,padding:"10px 13px",cursor:"pointer",fontWeight:650} as const;

export default function AgentPage(){
  const [token,setToken]=useState("");const [workspace,setWorkspace]=useState("");const [mode,setMode]=useState<Mode>("agent");const [task,setTask]=useState("");const [job,setJob]=useState<Job|null>(null);const [message,setMessage]=useState("Connect a Local Bridge, choose an approved workspace, then describe the coding task.");const [busy,setBusy]=useState(false);
  useEffect(()=>{setToken(sessionStorage.getItem("opentrue.control.token")||"");setWorkspace(localStorage.getItem("opentrue.agent.workspace")||"")},[]);
  useEffect(()=>{if(token)sessionStorage.setItem("opentrue.control.token",token)},[token]);
  useEffect(()=>{if(workspace)localStorage.setItem("opentrue.agent.workspace",workspace)},[workspace]);
  async function api(path:string,init:RequestInit={}){if(!token)throw Error("signed bearer token is required");const r=await fetch(`/api${path}`,{...init,headers:{authorization:`Bearer ${token}`,"content-type":"application/json",...(init.headers||{})},cache:"no-store"});const data=r.status===204?null:await r.json().catch(()=>({}));if(!r.ok)throw Error(data?.error||`${r.status} ${r.statusText}`);return data}
  async function submit(){if(!workspace.trim())return setMessage("Workspace path is required and must be inside Local Bridge approved roots.");if(!task.trim())return setMessage("Describe the task first.");setBusy(true);try{const requiresApproval=mode==="agent"||mode==="debug";const data=await api("/v1/jobs",{method:"POST",body:JSON.stringify({target:"local-bridge",task:mode,args:[workspace.trim(),task.trim()],requiresApproval,projectId:workspace.trim()})}) as Job;setJob(data);setMessage(requiresApproval?"Task created. Review it, then approve execution.":"Read-only task queued without a write approval gate.")}catch(e){setMessage(`Submit failed: ${String(e)}`)}finally{setBusy(false)}}
  async function action(kind:"approve"|"cancel"){if(!job)return;try{const data=await api(`/v1/jobs/${job.id}/${kind}`,{method:"POST",body:"{}"}) as Job;setJob(data);setMessage(kind==="approve"?"Execution approved.":"Task cancelled.")}catch(e){setMessage(`${kind} failed: ${String(e)}`)}}
  async function refresh(){if(!job)return;try{setJob(await api(`/v1/jobs/${job.id}`) as Job)}catch(e){setMessage(`Refresh failed: ${String(e)}`)}}
  useEffect(()=>{if(!job||terminal.has(job.status)||job.status==="WAITING_APPROVAL")return;const id=setInterval(()=>refresh(),1800);return()=>clearInterval(id)},[job?.id,job?.status,token]);
  const output=useMemo(()=>job?.receipt?.output?.map(x=>x.text).join("")||"",[job]);
  return <main style={{minHeight:"100vh",background:"#050b16",color:"#e5e7eb",fontFamily:"system-ui",padding:"18px clamp(12px,3vw,28px)"}}><div style={{maxWidth:980,margin:"0 auto",display:"grid",gap:14}}>
    <header style={{display:"flex",justifyContent:"space-between",gap:12,alignItems:"center",flexWrap:"wrap"}}><div><h1 style={{margin:"0 0 4px"}}>OpenTrue Agent</h1><div style={{color:"#94a3b8"}}>Ask · Plan · Agent · Debug · local/open-weight first</div></div><div style={{display:"flex",gap:12}}><a href="/" style={{color:"#93c5fd"}}>IDE</a><a href="/control" style={{color:"#93c5fd"}}>Control</a></div></header>
    <section style={{...card,borderColor:"#1d4ed8"}}><b>Status</b><p style={{marginBottom:0,color:"#bfdbfe"}}>{message}</p></section>
    <section style={card}><h2 style={{marginTop:0}}>1. Connection</h2><label>Signed token<input type="password" value={token} onChange={e=>setToken(e.target.value)} style={{...field,marginTop:6}} placeholder="Same token used by OpenTrue Control"/></label><label style={{display:"block",marginTop:12}}>Approved local workspace<input value={workspace} onChange={e=>setWorkspace(e.target.value)} style={{...field,marginTop:6}} placeholder="/absolute/path/to/project"/></label><small style={{display:"block",marginTop:8,color:"#94a3b8"}}>The Local Bridge resolves the real path and rejects paths or symlinks outside its configured approved roots.</small></section>
    <section style={card}><h2 style={{marginTop:0}}>2. Task</h2><div style={{display:"grid",gridTemplateColumns:"repeat(4,minmax(0,1fr))",gap:7}}>{(["ask","plan","agent","debug"] as Mode[]).map(x=><button key={x} onClick={()=>setMode(x)} style={{...btn,background:mode===x?"#2563eb":"#1f2937",color:"white",textTransform:"capitalize"}}>{x}</button>)}</div><textarea value={task} onChange={e=>setTask(e.target.value)} rows={7} style={{...field,resize:"vertical",marginTop:12}} placeholder={mode==="ask"?"Ask a question about this repository…":mode==="plan"?"Describe what you want planned…":mode==="debug"?"Describe the failing behavior or test…":"Describe the change. The agent can search, edit, run checks and iterate…"}/><button onClick={submit} disabled={busy} style={{...btn,background:"#2563eb",color:"white",marginTop:10}}>{busy?"Submitting…":"Send to Local Bridge"}</button><p style={{color:"#94a3b8",fontSize:13}}>{mode==="ask"||mode==="plan"?"Read-only mode: no file edits.":"Write-capable mode: job stops at WAITING_APPROVAL before execution."}</p></section>
    {job&&<section style={card}><h2 style={{marginTop:0}}>3. Execution</h2><div style={{display:"flex",gap:8,flexWrap:"wrap",alignItems:"center"}}><strong>{job.status}</strong><code style={{color:"#94a3b8"}}>{job.id}</code></div><div style={{marginTop:10}}>{job.status==="WAITING_APPROVAL"&&<button onClick={()=>action("approve")} style={{...btn,background:"#059669",color:"white",marginRight:8}}>Approve</button>}<button onClick={refresh} style={{...btn,background:"#374151",color:"white",marginRight:8}}>Refresh</button>{!terminal.has(job.status)&&<button onClick={()=>action("cancel")} style={{...btn,background:"#991b1b",color:"white"}}>Cancel</button>}</div>{job.error&&<pre style={{whiteSpace:"pre-wrap",color:"#fca5a5"}}>{job.error}</pre>}{output&&<pre style={{whiteSpace:"pre-wrap",overflowWrap:"anywhere",background:"#020617",border:"1px solid #1e293b",padding:12,borderRadius:8,maxHeight:420,overflow:"auto"}}>{output}</pre>}{job.receipt&&<div style={{fontSize:13,color:"#94a3b8"}}>Exit {job.receipt.exitCode} · {job.receipt.durationMs} ms · receipt {job.receipt.outputHash?.slice(0,16)||"n/a"}</div>}</section>}
    <section style={{...card,color:"#cbd5e1"}}><b>Acceptance rule</b><p style={{marginBottom:0}}>A task is counted as executed only when the control-plane reports a terminal worker receipt. UI submission alone is not treated as proof.</p></section>
  </div></main>
}
